### ISSUE TITLE
[Platform-Dependencies] Remove Sphinx constraint and fix docs build

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/public-engineering#161]
### Description 
- Remove `Sphinx` constraint and fix the failing `docs` build occurring due to new `sphinx` and `doc-utils` version.
- Also remove the `sphinxcontrib-openapi[markdown]` constraint from [development.in](https://github.com/openedx/edx-platform/blob/master/requirements/edx/development.in#L21) file which was present because of Python3.6 requirement.

### Error Stack Trace 
```
WARNING: autodoc: failed to import module 'urls' from module 'cms'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 58, in import_module
    return importlib.import_module(modname)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/edx-platform/edx-platform/cms/urls.py", line 188, in <module>
    if not settings.DISABLE_DEPRECATED_SIGNIN_URL:
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DISABLE_DEPRECATED_SIGNIN_URL'

```

**Comment by UsamaSadiq** [comment]
Investigated the issue and created PR https://github.com/openedx/edx-platform/pull/31152 to fix this issue.
